import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const A='/Kashu-Birthday/media/';
const hours=[
{h:1,time:'12:00 AM',title:'The beginning of us',k:'letter',img:'photo01.jpeg',text:`Babe,\nThis is my first birthday with you, and today I want to spend every hour reminding you how much I love you. ❤️\n\nSo for our first hour, let's go all the way back to the beginning.\n\nI still remember the first time I saw you on that scooty. I was literally drenched in sweat, looking absolutely finished… but somehow, your beauty still managed to distract me completely. 😂❤️\n\nI don't know what it was about that moment, but I remember feeling something.\n\nMaybe it really was love at first sight. ❤️\n\nBecause little did I know that the girl I noticed that day would become my Kashu, my favourite person, and the person I love the most. ♡\n\nAnd this is only the beginning…\nThere are still so many pieces of our story I want to tell you.`},
{h:2,time:'1:00 AM',title:'The beginning we didn’t know was beginning',k:'film',img:'photo02.jpeg',video:'video02.mp4',text:`I still think about how simple our first meeting was.\n\nJust you, me, a shawarma, and two people slowly getting to know each other. ❤️\n\nWe didn't know it then… but somewhere between those little conversations, the laughs, and those simple moments, something was quietly beginning.\n\nI wasn't thinking about where it would lead. I was just enjoying being around you.\n\nAnd somehow, without either of us realizing it, those little moments became the beginning of us. ❤️\n\nLooking back now, it's crazy to think that one simple day would eventually lead me to my favourite person.\n\nAnd honestly… I'd choose that first meeting all over again.`},
{h:3,time:'2:00 AM',title:'The little things I fell for',k:'soft',img:'photo03.jpeg',text:`It wasn't one huge moment that made me fall for you.\n\nIt was all the tiny things.\nThe way you care. The way you remember things. The way you make ordinary moments feel special.\n\nThe more I got to know you, the more I realised there was something about you I didn't want to lose.\n\nAnd somehow, little by little… you became my person. ❤️`},
{h:4,time:'3:00 AM',title:'Our unofficial love language: annoying each other 😂',k:'chaos',img:'photo04.jpeg',video:'video04.mp4',text:`You know exactly how to annoy me. 😂\n\nAnd somehow I know exactly how to annoy you back.\n\nThe ragebaiting. The stupid arguments. The “I'm not talking to you” moments. The drama.\n\nAnd then five minutes later… we're back to being us. 😂❤️\n\nMaybe that's one of the funniest things about us.\nWe can be absolute idiots together and still somehow feel completely at home.`},
{h:5,time:'4:00 AM',title:'Your favourite colour looks better on you',k:'pink',img:'photo05.jpeg',text:`I know you love pink. ❤️\n\nBut honestly, I think every colour looks better when you're wearing it.\n\nI love seeing you dress up, change your style, try something new, and somehow make it look like it was made for you.\n\nYou're beautiful when you're dressed up.\nYou're beautiful when you're not trying.\n\nAnd yes… I will keep admiring you every single time.`},
{h:6,time:'5:00 AM',title:'Our song, our little world',k:'music',img:'photo06.jpeg',text:`There are some songs you hear… and then there are songs that become memories.\n\n“Singara Siriye” will always remind me of you. ❤️\n\nBecause now whenever I hear it, somewhere in my head there's a version of us — laughing, dancing, looking at each other, just being us.\n\nI hope we keep collecting songs like that for the rest of our lives.`},
{h:7,time:'6:00 AM',title:'The way you take care of me',k:'care',img:'photo07.jpeg',text:`You don't always realise how much you do for me.\n\nThe small check-ins. The little reminders. The way you notice when something is wrong. The way you make sure I'm okay.\n\nYou make me feel cared for in ways I sometimes don't know how to put into words.\n\nAnd I hope you know that I notice.\nI appreciate you.\nAnd I love you for it. ❤️`},
{h:8,time:'7:00 AM',title:'The way you make me feel',k:'intimate',img:'hour08.jpeg',text:`Your smile. The way you make me feel special.\n\nI love getting kisses from you.\nI love feeling hugged by you.\nI love laying with you.\n\nThere is something about being close to you that makes everything else feel quiet.\n\nI don't need anything fancy. Sometimes I just want you next to me, your arms around me, and that feeling of being home. ❤️`},
{h:9,time:'8:00 AM',title:'Things I never said out loud',k:'private',img:'hour09.jpeg',text:`I am a very private person, babes. 😂\n\nI don't show our relationship to the world as much as you sometimes want me to. But honestly… I like us being private.\n\nLove in private. ❤️\nKisi ki nazar na lage. 🧿\n\nBut the funny part is… when I'm with you, there is absolutely no privacy. 😂\n\nWith you, my love is completely open. You get all of me — the stupid, emotional, annoying, loving version of me.`},
{h:10,time:'9:00 AM',title:'Our adventures',k:'adventure',img:'hour10.jpeg',video:'video03.mp4',text:`Do you remember our first concert? Holi?\n\nIt was so much fun — and even more fun because it was FREE. 😂😂\n\nBut what made it special for me was you introducing me as your boyfriend.\n\nIt felt so new. So simple. But so special. ❤️\n\nThe first time we danced together.\nThe beautiful location.\nThe beautiful vibe.\n\nThese are the moments I want to keep collecting with you.`},
{h:11,time:'10:00 AM',title:'When we were us',k:'photos',img:'hour11.jpeg',video:'video01.mp4',text:`You love clicking photos. ❤️\n\nAnd me? I love giving you the weirdest poses possible. 😂\n\nSome of our cutest pictures are the ones where we're not even trying.\n\nJust two idiots being comfortable enough to be completely ourselves.\n\nI hope we never stop taking stupid pictures together — because one day these random photos will be some of my favourite memories.`},
{h:12,time:'11:00 AM',title:'Halfway: why I choose you',k:'halfway',img:'hour12.jpeg',text:`You are my supporter.\nMy cheerleader.\nMy pillow. 😂\nMy strength.\nMy coach.\nMy English teacher. 😂\nMy lover. ❤️\n\nYou somehow manage to be so many things for me at once.\n\nAnd that's one of the reasons I choose you.\nNot because everything is perfect — but because with you, I feel like I can keep becoming better.`},
{h:13,time:'12:00 PM',title:'My hottie ❤️',k:'beauty',img:'hour13.jpeg',text:`You don't appreciate yourself enough sometimes.\n\nBut I do. ❤️\n\nI see you. I notice your smile, your eyes, your expressions, your little mannerisms — all of it.\n\nTo me, you are the most beautiful girl.\nThe one I admire.\nThe one I can't stop looking at.\n\nSo yes, babes… you're my hottie. And I will continue reminding you until you finally believe me. 😂❤️`},
{h:14,time:'1:00 PM',title:'Our love language: food',k:'food',img:'hour14.jpeg',text:`We love food. 😂❤️\n\nTrying new places.\nEating. Drinking.\nOrdering things we probably didn't need.\nTaking pictures before eating. 😂\n\nThere is something so fun about discovering new places with you.\n\nHonestly, give me good food, a new place and you sitting across from me… and I'm happy.`},
{h:15,time:'2:00 PM',title:'Why everyone loves you',k:'friends',img:'hour15.jpeg',text:`You are sabki favourite. ❤️\n\nEveryone wants to hang out with you.\nEveryone wants to spend time with you.\n\nBecause you're funny. You're fun-loving. You make people comfortable. You bring energy wherever you go.\n\nAnd I love watching people love you — because I know exactly why they do.\n\nYou're just… you. And that's pretty special.`},
{h:16,time:'3:00 PM',title:'My singer. My heroine. My drama queen. 😂❤️',k:'transition',img:'photo16.jpeg',video:'video07.mp4',text:`I love seeing your videos.\n\nOne moment you're acting like the heroine of a movie.\nThen you're singing like you're on stage.\nThen you're doing a transition like a model.\nThen suddenly you're being the biggest drama queen. 😂\n\nAnd I love every version of it.\n\nI love watching you be confident, expressive, silly and completely yourself.\n\nKeep making those videos, babes. I'll keep being your number-one viewer. ❤️`},
{h:17,time:'4:00 PM',title:'A letter of promise',k:'promise',img:'photo17.jpeg',text:`Babe,\n\nI promise to stay with you for as long as I can.\nI promise to be better for you.\nI promise to be better with you.\nI promise to make you laugh.\nI promise to keep you safe.\nI promise to work hard.\n\nThis isn't a promise that I'll always be perfect. I won't be.\n\nIt's a promise that I will keep trying.\nI want to see you become the strongest, happiest and best version of yourself.\n\nAnd I want to be beside you while you do it. ❤️`},
{h:18,time:'5:00 PM',title:'I’m sorry for the things I get wrong',k:'apology',img:'hour18.jpeg',video:'video05.mp4',text:`Babe, as I write this, I'm getting more and more emotional.\n\nI know I will probably cry as I move forward because these are some of the most emotional moments I've spent with you.\n\nI want you to always smile, babes. Don't cry because of me. ❤️\n\nI'm not the boy you always wished for. I'm not always as supportive as I should be. I don't always assure you. I don't always post. And I know I do stupid things.\n\nI'm sorry for everything I get wrong.\n\nBut please never mistake my mistakes for a lack of love.\nI love you deeply. And I am still learning how to love you better.`},
{h:19,time:'6:00 PM',title:'I miss you. Always.',k:'miss',img:'hour19.jpeg',video:'video06.mp4',text:`There are moments when I don't say it, but I miss you.\n\nWhen you're not around, I notice the empty space.\nI miss your voice.\nI miss your hugs.\nI miss lying next to you.\nI miss the stupid conversations.\nI miss just having you around.\n\nAnd sometimes I don't even need a reason.\n\nI just miss you, Kashu. ❤️`},
{h:20,time:'7:00 PM',title:'The future we are not sure of',k:'future',img:'hour20.jpeg',text:`We don't know exactly what the future looks like.\n\nAnd honestly, that can be scary.\n\nBut I always imagine a future with you. I try for that, even when I don't know whether everything will work out exactly the way we imagine.\n\nMaybe we'll have difficult days. Maybe we'll have to fight for things.\n\nBut if we're fighting for our future, I want to stand with you.\n\nWhatever comes, I want us to face it together. ❤️`},
{h:21,time:'8:00 PM',title:'A language isn’t enough to say “I love you”',k:'languages',img:'hour21.jpeg',text:`Yaan ninada priti malpuye ❤️\n\nMoi tomak bhal pao.\nAmi tomake bhalobashi.\nHam tohar se pyaar karila.\nHu tane prem karu chu.\nMain tumse pyaar karta hoon.\nNaanu ninnannu preetisuttene.\nMi tujhyaavar prem karto.\nNaan unnai kaadhalikiren.\nNenu ninnu premistunnaanu.\nNjan ninne snehikkunnu.\n\nDifferent languages. Different words.\n\nBut somehow they all mean the same thing.\n\nI LOVE YOU. ❤️`},
{h:22,time:'9:00 PM',title:'Everything you mean to me',k:'everything',img:'hour22.jpeg',text:`Babe,\n\nI don't think there is one word big enough to explain what you mean to me.\n\nYou are not just my girlfriend. You're my favourite person, my comfort, my happiness, my home.\n\nYou're the person I want to tell everything to. The person I want beside me when life is amazing, and especially when it isn't.\n\nYou make ordinary days feel special just by being there.\n\nYou make me laugh. You annoy me. 😂 You take care of me. You listen to me. You believe in me. You love me in ways I sometimes don't even know how to explain.\n\nAnd somewhere along the way, you became a part of almost everything I imagine for myself.\n\nYou mean everything to me, Kashu. ❤️`},
{h:23,time:'10:00 PM',title:'One last memory before midnight…',k:'cranky',img:'hour23.jpeg',text:`Babe, 😂❤️\n\nOf course I couldn't finish our 24 hours without talking about one of my favourite versions of you…\n\nCranky Kashu. 😂\n\nThat little face you make when you're annoyed, the attitude, the drama, the expressions…\n\nAnd somehow, even when you're being cranky, I still find you ridiculously cute. ❤️\n\nI love your happy face. I love your excited face. I love your sleepy face.\n\nBut honestly… I think I secretly love your cranky face the most. 😂❤️\n\nBecause every version of you is still my favourite girl.`},
{h:24,time:'11:00 PM',title:'The last bouquet — but not the last chapter',k:'final',img:'hour24.jpeg',text:`Kashu,\n\nAnd just like that… 24 hours. 24 bouquets. 24 little pieces of us. ❤️\n\nIf you've made it this far, I hope you've smiled, laughed, maybe cried a little, and remembered all the tiny moments that brought us here.\n\nBut there's one thing I haven't told you enough.\n\nOut of everything life could have given me, I'm most grateful that it gave me you.\n\nI don't know what every tomorrow is going to look like. I don't know where life will take us, what we'll achieve, what we'll fight about, how much we'll grow, or how many crazy stories we'll have left to make.\n\nBut I know one thing.\n\nI want to keep making those memories with you.\n\nMore stupid pictures. More random food dates. More dancing. More travelling. More arguments over absolutely nothing. 😂 More kisses. More hugs. More “Ayush, you're so annoying.” And definitely more cranky Kashu. 😂❤️\n\nYou became my favourite part of my life without me even realizing when it happened.\n\nAnd if these 24 bouquets were my way of giving you a little piece of my heart every hour… then this last one is all of it.\n\nHappy Birthday, my Kashu. ❤️\n\nI love you.\n\nNot just for who you are today, but for every version of you I'm lucky enough to meet along the way.\n\nThis isn't the end of our story. It's just the end of the first 24 hours.\n\nOur story has so much more to come. ❤️\n\nHappy Birthday, babe.\nI choose you.\nToday. Tomorrow. And every day I get to. ❤️\n\n— Ayush ♡`}
];

function Petals(){return <div className="petals" aria-hidden>{Array.from({length:18},(_,i)=><span key={i} style={{'--i':i}}>{i%3===0?'❤':i%3===1?'✦':'❀'}</span>)}</div>}
function Media({item}){return <div className="media-wrap">
  <div className={'photo-frame '+item.k}><img src={A+item.img} alt="A memory of us"/></div>
  {item.video && <details className="video-drawer"><summary>Open the little video memory 🎞️</summary><video src={A+item.video} controls playsInline preload="metadata"/></details>}
</div>}
function App(){
 const [open,setOpen]=useState(false); const [index,setIndex]=useState(0); const [preview,setPreview]=useState(()=>new URLSearchParams(window.location.search).get('preview')==='1'); const [menu,setMenu]=useState(false); const [seen,setSeen]=useState([1]);
 const nowHour=new Date().getHours(); const current=Math.min(24,nowHour+1);
 const item=hours[index];
 const unlocked=preview?24:current;
 const next=()=>setIndex(i=>{const n=Math.min(23,i+1); setSeen(v=>v.includes(n+1)?v:[...v,n+1]); return n}); const prev=()=>setIndex(i=>Math.max(0,i-1));
 useEffect(()=>{const onKey=e=>{if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev();if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 if(!open)return <div className="app landing"><Petals/><div className="hero-card reveal"><div className="tiny">FOR KASHU · FROM AYUSH</div><div className="bouquet-mark">🌹</div><div className="eyebrow">A birthday made one hour at a time</div><h1>24 Hours<br/><em>of Us</em></h1><p className="lead">Twenty-four bouquets. Twenty-four memories. One girl who means everything to me.</p><div className="rule"/><p className="small">Every hour has a little piece of my heart waiting for you.<br/><span>Open this again whenever you want to remember us.</span></p><button className="primary" onClick={()=>setOpen(true)}>Open your first bouquet <span>♡</span></button><div className="signature">Ayush ♡</div></div></div>;
 return <div className={'app page theme-'+item.k}><Petals/><header><button className="brand" onClick={()=>setOpen(false)}>K ♡ A</button><div className="hour-chip">BOUQUET {item.h} / 24</div><button className="menu" onClick={()=>setMenu(v=>!v)}>☰</button></header>
 {menu&&<div className="menu-panel"><div className="menu-title">24 little pieces of us</div>{hours.map((x,i)=>{const locked=!preview&&x.h>unlocked; return <button key={x.h} disabled={locked} className={i===index?'active':''} onClick={()=>{setIndex(i);setMenu(false)}}><span>{String(x.h).padStart(2,'0')}</span><span>{x.title}</span>{locked&&<small>locked</small>}</button>})}</div>}
 <main><div className="time">{item.time} <span>·</span> for Kashu</div><div className="title-row"><h2 key={item.h} className="title-enter">{item.title}</h2><span className="mini-flower">{item.k==='final'?'🌹':'✦'}</span></div>
 <div className="memory-tag"><span>BOUQUET {String(item.h).padStart(2,'0')}</span><span>♡</span><span>{seen.includes(item.h)?'A memory you can keep':'Waiting for you'}</span></div><div className="content-grid"> <Media item={item}/><article className="letter-card">{item.k==='final'&&<div className="final-rose">🌹</div>}<div className="letter-text">{item.text.split('\n').map((t,i)=><React.Fragment key={i}>{t}{i<item.text.split('\n').length-1&&<br/>}</React.Fragment>)}</div>{item.k==='languages'&&<div className="love-word">I LOVE YOU</div>}{item.k==='promise'&&<div className="promise-line">I promise to keep choosing you. ❤️</div>}{item.k==='everything'&&<div className="promise-line">You mean everything to me.</div>}{item.k==='final'&&<div className="final-line">24 bouquets down.<br/><span>A lifetime of memories to go.</span></div>}</article></div>
 <div className="controls"><button className="nav-btn" disabled={index===0} onClick={prev}>← Previous</button><button className="counter-btn" onClick={()=>setMenu(true)}>{item.h} / 24</button><button className="nav-btn primary-nav" disabled={item.h>=unlocked} onClick={next}>{item.h===24?'The end ❤️':'Next hour →'}</button></div>
 <div className="progress"><span style={{width:`${item.h/24*100}%`}}/></div><p className="footer-note">Made with too much love, a little drama, and 24 memories. ♡</p></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
